### ISSUE TITLE
Option to optimize screen space

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#10]
It would imply moving small windows around, like for instance putting them in quarters instead of half screen, so other non-small windows can benefit of the extra space

Perhaps even adding small windows together within a quarter if they would fit the available space.

**Comment by ghost** [comment]
Have you attempted using the "Small Windows" section of the config? Adding the windows where they are "Small" may allow it to auto move to a quarter? The issue being with this is that all 4 quarters have to be used , so if you open a half screen application then a small app, it will default to the half size until a third window is open.

Do you perhaps mean having it that, by default, if a small window is opened as the third app, it moves to a quarter instead of opening as the Half App by default?

**Comment by kupiqu** [comment]
> Do you perhaps mean having it that, by default, if a small window is opened as the third app, it moves to a quarter instead of opening as the Half App by default?

Yes, this comes from discussion within another issue (see below). We just moved it here so we can track it better

https://github.com/Jazqa/kwin-quarter-tiling/issues/5#issuecomment-318658137

**Comment by Jazqa** [comment]
Been actively working on this. The current implementation is still a little rough, but I'm slowly starting to figure out the way I want to approach the issue. I've barely touched moving and resizing small clients yet, so it's a work-in-progress. It'll probably take a few days. 

On other news, I added the option to tile small clients according to the screen or the tiles.

**Comment by kupiqu** [comment]
Excellent, as usual :)

**Comment by kupiqu** [comment]
Also, the window of the script settings could be improved a bit for (I guess) screens of high resolution. Could you please take a look to the screenshot below? It's a really minor thing though...

![image](https://user-images.githubusercontent.com/3875196/28898911-420e1c9a-77b6-11e7-8d16-8deccf6944c1.png)

Edit: for the case I wasn't clear enough, I meant about text boxes for "Gap size" and "Margins".

**Comment by Jazqa** [comment]
Huge commit today. Might have screwed everything up, who knows. My brain feels like pudding. Anyways, I created a new configuration UI and added an option for optimizing screen space (called Autosize in the options menu). Enabling "Autosize" makes the script automatically size windows according to small programs. It might feel a little confusing, feedback appreciated.

**Comment by kupiqu** [comment]
Testing it. I'll let you know if I find glitches, etc. :)

**Comment by kupiqu** [comment]
Would it be difficult to set small windows within the same quarter if they would fit? Please see the screenshot below

<img width="1253" alt="screenshot_20170803_231339" src="https://user-images.githubusercontent.com/3875196/28952843-f8b36892-78a1-11e7-8674-86ce59c6af91.png">

**Comment by Jazqa** [comment]
Depending on the approach, it can be extremely difficult but it's something I definitely want to do when I have the time (might take a while). 

Two possible approaches: 

1. Split the tile into two tiles. Doing this, the script stops being a "quarter" tiling script and turns into an actual tiling script (as I can allow the user split regular tiles if they so wish).

2. Have the fourth tile detect space near the third one and slide it there, moving the third one to the edge of the tile and making space for the first tile to expand down. Having the tiles move from the edges will mess with the calculations, so I'll have to see how feasible this approach is.

Anyways, I won't be able to implement a change this big for a week or two, unless I figure a rock solid way to do it, but at some point, I definitely will.

**Comment by kupiqu** [comment]
Sounds good, thank you!

I for one like quarter tiling a lot for windows in general, but I also like special tiling for small clients. So ideally, for me, a virtual desktop shouldn't be split in more than 4 quarters, yet small clients would be able to occupy the same quarters, according to their dimensions. Technically, this may be very hard to achieve though :/

Thanks a lot for working on this.

**Comment by kupiqu** [comment]
I think this is out of scope in the new implementation and I'm totally fine closing the issue if you consider it proper.

**Comment by kupiqu** [comment]
I'll just close this :)
