### ISSUE TITLE
The configs keep persisting in shortcuts even after uninstalling. 

### ISSUE THREAD

**Issue by ayushsherpa111** [Jazqa/kwin-quarter-tiling#100]
Distro: KUbuntu

I decided to uninstall the script by using the script that was on the readme, but even after that the configs for quarter still appears in the system settings. I looked for any files that may still be around but couldnt find any.

![image](https://user-images.githubusercontent.com/35552818/103170533-f8a28380-486c-11eb-9173-73adca82ff7f.png)

**Comment by Jazqa** [comment]
Hello! Yes, this is unfortunately out of my control and also causing issues when renaming the shortcuts. All of the shortcuts can be found inside a KWin configuration file under `~/.config` folder. I do not remember the exact name of the file, nor do I have access to a KDE machine to confirm this, but I think it's something like `kglobalshortcutsrc` or `khotkeysrc`.

**Comment by ayushsherpa111** [comment]
indeed the filename was `kglobalshortcutsrc`. i have deleted it from there, but i think i might have to restart my machine to confirm that it is all gone. thanks for your reply :)

**Comment by Jazqa** [comment]
That'll also delete all of your other custom shortcuts (KWin and KDE). You can just open the file with a text editor and remove everything starting with `Quarter:`.

**Comment by ayushsherpa111** [comment]
Yes that is what i did lol.

**Comment by Jazqa** [comment]
`qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.cleanUp`
