### ISSUE TITLE
Nonsensical keyboard shortcuts

### ISSUE THREAD

**Issue by wolfisdev** [Jazqa/kwin-quarter-tiling#102]
Hi,

I just started using this script and I see a lot of potential in it. Thanks for developing it!

I just can't seem to wrap my head around some keyboard shortcut options.

Why are there four separate options to horizontally resizing windows?
- Increse size left window
- Decrease size left window
- Increase size right window
- Decrease size right window

Since resizing the window causes the adjacent window to resize as well in order to fit, wouldn't it make more sense to have just two options, either
- Increase size left window
- Decrease size left window
or
- Increase size left window
- increase size right window
or even better
- Increase size current/focused window
- Decrease size current/focused window

My issue stems from the fact that, when trying to resize the left window while focus is on the right window, nothing happens (and vice versa). And since you can't bind resizing left and right to the same short cuts, it means you'd have to assign 4 shortcuts and think about which ones to use while 2 of them seem to have the same outcome anyway (granted they'd work independent of focus).

Of course all of the above applies to vertical resizing as well.

Thanks for considering.

**Comment by Jazqa** [comment]
I vaguely remember struggling with resize shortcuts, but I can't remember the exact reason for the current solution. Quickly skimming through the code would suggest that simplifying them is possible, but I'll have to do some actual testing first.
