### ISSUE TITLE
Three vertical split

### ISSUE THREAD

**Issue by Bleighhhh** [Jazqa/kwin-quarter-tiling#110]
Would be possible to add a three vertical split as an extra option to the auto tiling we already have?

**Comment by Jazqa** [comment]
It's definitely possible. I'm not running KDE at the moment, so I'll need to find some time for setting up a VM.

If you're familiar with Javascript, the layouts are located in [src/layouts](https://github.com/Jazqa/kwin-quarter-tiling/tree/master/src/layouts) and are relatively simple (although the documentation could be improved).

**Comment by Bleighhhh** [comment]
> It's definitely possible. I'm not running KDE at the moment, so I'll need to find some time for setting up a VM.
> 
> If you're familiar with Javascript, the layouts are located in [src/layouts](https://github.com/Jazqa/kwin-quarter-tiling/tree/master/src/layouts) and are relatively simple (although the documentation could be improved).

Not familiar with JS and codiing at all, but willing to learn for some time now. If I understand how to experiment without breaking your script I will try, but if you do, it would be much appreciated <3

**Comment by Bleighhhh** [comment]
> It's definitely possible. I'm not running KDE at the moment, so I'll need to find some time for setting up a VM.
> 
> If you're familiar with Javascript, the layouts are located in [src/layouts](https://github.com/Jazqa/kwin-quarter-tiling/tree/master/src/layouts) and are relatively simple (although the documentation could be improved).

ehy!
I am trying to understand how to do it and I will try to do it copying from your layout alrrady made and a three column layout from another script. I don't the the src directories on my laptop tho. How should I proceed to experiment with the 3 column layout addition? 

moreover, I have a new machine running your script, here I cannot resize windows like I do with the older machine which still runs your script, do you have any idea of what am I missing? thank you for your time

**Comment by kupiqu** [comment]
> I cannot resize windows

I see the same bug (you should probably open a different issue for this though). It may very well be related with the change added (f2fd199791546f697c396c36f9f8eedfa01a207a) to make the script work in Plasma 5.22 (issue #105)

**Comment by Jazqa** [comment]
Alright, looks like I'm about to switch to KDE anyways – I'll implement the new layout while I'm fixing the resizing issue.

Either way, to answer your original question – the two machines may be running a different version (older versions don't use Typescript and thus don't have the `src` folder) or you may have installed the script via KDE store. Either way, the easiest way to play around is to install the script via git – run `npm install` on the script's folder and modify one of the existing layouts. After changes to the layout, run `npm run transpile` and restart the script for the changes to take effect.

**Comment by techmouse** [comment]
I came here looking for exactly this. Quarter tiling is fine for 4:3 but widescreen is a different breed. There's simply too much screen real-estate space to only have 4 programs per virtual desktop. 

Having more control over how many windows are allowed for every virtual desktop would be a godsend. I can't wait to see what future versions will look like.

**Comment by Jazqa** [comment]
Added layouts for rows and columns.
