### ISSUE TITLE
Spectacle does not follow tiling rules

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#12]
Spectacle is the new screenshot application in kde. I noticed that it does not follow tiling.

**Comment by Jazqa** [comment]
This is intentional. KWin categorizes windows to different categories like docks, menus and toolbars. Spectacle falls into the category "transient", which consists of windows that are not supposed to exist for long and are thus ignored.

**Comment by kupiqu** [comment]
I see. Thanks for the clarification!
