### ISSUE TITLE
Windows that are on the same virtual desktop, but on different activities act as if each other is present

### ISSUE THREAD

**Issue by noahadvs** [Jazqa/kwin-quarter-tiling#13]
Here's a 23 second video demonstrating the issue.
https://www.youtube.com/watch?v=yMG1SXnkwlQ

**Comment by Jazqa** [comment]
I've completely ignored Activities thus far. When I started, multiple virtual desktops and screens were enough headache already. However, I think I'm ready for activities now. I'll see if I can add the activities-support today.

EDIT: Got overwhelmed with other things, sorry. I'll fix it first thing tomorrow!

**Comment by Jazqa** [comment]
Turns out activities are not supported by the KWin scripting API as well as virtual desktops are, which will result in a weak activities support of the script. It's a shame actually, activities would have played nicely with my script if KWin worked the same way with activities as it does with virtual desktops.

I should be able to add basic activities support for the script, but I don't know if I can make switching the activity of a window or pinning a window to multiple activities work properly (pinning a window to multiple activities will keep the window tiled according to the activity it was created on).

EDIT: I might be able to add support for pinning across the activities and adding multiple activities but it'll take a while.

**Comment by Jazqa** [comment]
Started working on this. Available via "activities" branch. I'll merge it with master when all the features are working. Next week is going to be extremely busy, so full activities support might take longer than a week.

-----------------------
Progress:
- [x] Basic support for multiple activities
- [x] Activity creation & removal while the script is running
- [ ] Interaction between activities (moving windows between activities and pinning windows on multiple activities)

**Comment by noahadvs** [comment]
The weak activity support is indeed unfortunate, but I really do appreciate the effort you put into this script.

**Comment by Jazqa** [comment]
Well, it's understandable as windows are able to exist on multiple activities simultaneously. I'm still exploring the API for signals regarding the activity changes and I'll see what I can do. In its current state, the branched script fixes the issue in your video and supports multiple activities, as long as you keep the activities separate and do not switch windows between them. I'll probably add activity creation and removal later today.

> I really do appreciate the effort you put into this script

Well, it's great programming practice! I also enjoy working on it and am delighted when people help me by filing issues and suggesting features. I rarher learn programming by creating something that me and other people can use than by creating a thousand completely useless programs.

**Comment by kupiqu** [comment]
> it's understandable as windows are able to exist on multiple activities simultaneously

I wonder how much this is different compared to virtual desktops. Perhaps worth trying to discuss this with Kwin dev, Martin Gräßlin?

**Comment by Jazqa** [comment]
I've actually found all the tools I need. It's totally doable but it's a hell of a job. I'll try to implement everything except the interaction between the activities today and merge activities branch with master. I'll leave the interaction between the activities for later.

Virtual desktops are listed as client properties (integer) and if a client is bound to all desktops, its desktop is simply -1. Activities are listed as client properties as well, but as an array, so I'll have to iterate through all of the client's activities whenever adding, removing and changing the desktops of clients, making it all a bit difficult. On top of this, I'll have to add a bunch of exceptions for cases where a client would have different desktops on different activities.

**Comment by Jazqa** [comment]
Merged the activities branch with master and the behaviour in the original video should work now. Working too late makes me a little absent-minded, so hopefully there aren't too many bugs left. Activity creation and removal should work with the script running as well, although removing an activity is still a little unstable.

**Comment by kupiqu** [comment]
Everything seems to work nicely!

I had to restart my session to make it work properly though (Just saying for the case someone else finds the same issue). More specifically, tiling failed and shortcuts didn't work. Restarting kwin and plasmashell didn't seem to help, so I restarted the session and everything came back to normal.

**Comment by noahadvs** [comment]
The behavior demonstrated in the video I made seems to be fixed for me as well. Thanks @Jazqa!

**Comment by Jazqa** [comment]
I'll close this one as the issue in the video has been solved. New one can be opened for interaction between the activities.
