### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#16]
Not urgent, as Plasma in wayland is still far from working flawlessly, but anyways. I just checked the current state of plasma wayland and realized that the kwin-quarter-tiling script does not work properly.

It worked for my first window and stopped being applied to windows opened afterwards.

**Comment by Jazqa** [comment]
Did the first window stay tiled? If yes, this should be easy to fix.

**Comment by kupiqu** [comment]
Yes, the first one was tiled all the time

**Comment by Jazqa** [comment]
It's not the first one that gets and stays tiled. It's all of the GTK ones. I finally got Wayland running today and looked into this but I'm not sure if I can do anything about it until KWin gets updated. All of the GTK programs get tiled properly, but the script doesn't notice Qt programs at all.

**Comment by Jazqa** [comment]
Since there's no change in 5.11, I filed an issue about this to the KDE bug tracker. Hopefully we'll get a fix by 5.12.

**Comment by kupiqu** [comment]
Thanks!

Could you please add here the link to the bug in KDE?

**Comment by Jazqa** [comment]
It's apparently going to be [fixed later](https://bugs.kde.org/show_bug.cgi?id=385595). The script should automatically start working with Wayland once it's fixed.

**Comment by Futureknows** [comment]
Has the Wayland compatibility been resolved? I installed and can't get tiled windows to resize together, continues to behave like default Plasma. Tried hotkeys, not a lot of documentation.

**Comment by Jazqa** [comment]
@Futureknows, I doubt the issue has progressed at all. I'll have to try to be certain though.

**Comment by Ch4tul** [comment]
@Jazqa the status of the KDE Bugtracking changed recently to "Resolved Fixed", perhaps you can get quarter working in wayland now
