### ISSUE TITLE
Konsole initially opens with border when border = false

### ISSUE THREAD

**Issue by vegarab** [Jazqa/kwin-quarter-tiling#22]
First Konsole window to be opened opens with border. If it is closed, then reopened, it is opened without a border. If you then go ahead and close it and open it a third time, it will have a border, then next time it will not. In other words, it systematically opens without a border on every even launch, and with a border on every odd launch.
When there is a Konsole window open, all new Windows will have the same setting as the first one. E.g. if there is a Konsole window open that does not have a border, all new Konsole windows follow suit and have no border.

This persists even when Konsole is set to have no border by right-clicking Titlebar -> More actions -> No border.

KDE Neon Use Edition, Plasma 5.10

**Comment by vegarab** [comment]
I would have made a gif to show the behaviour, but I haven't found any applications that allow me to record gifs that don't crash the script.

**Comment by Jazqa** [comment]
Are you still using the Active Window Controls' "Hide Maximized Titlebars" option? I've been exploring this issue today myself and I've come to the conclusion that window borders are a mess. Active Window Controls, KWin's Window Rules and Breeze's Window Decoration Options all interfere with the borders, as does my script. I'm probably just dropping the border manipulation altogether from the script and leaving it to KWin, Breeze and Active Window Decoration. By far the most stable and clean solution. 

Also, which recording programs are crashing the script? Kazam and Simple Screen Recorder have both worked for me. If a program is breaking the script, just add it to the "Ignored Programs" list and everything should be fine.

**Comment by vegarab** [comment]
The "Hide Maximized Titlebars" options make no functional difference once you have the border set to false in the script. Disabling it in Active Window Manager solved the problem with Konsole, but the titlebar still merges with the top panel. Problem solved.

Perhaps Active Window Manager merges the titlebar whenever there is no border on the window you maximize, but does not interfere with the script when it's own option is disabled. Otherwise, there would be no way of minimizing the window without adding the border on the window again.

**Comment by Jazqa** [comment]
I'm removing the "Borders" option from the script in the next commit. There are multiple other ways to disable the borders and the script setting is causing multiple unnecessary bugs. In my experience, the best way to disable borders is through "Window Decoration" as seen in the picture below (the `.*` in the picture hides the borders of all windows).

![image](https://user-images.githubusercontent.com/18004783/29276045-f64278ba-8115-11e7-99b2-7efe651e9efc.png)

**Comment by Jazqa** [comment]
Closing this as the "Borders" option has been deprecated.
