### ISSUE TITLE
Allow Regular Expressions in Ignored Window Captions

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#25]
Regarding Matlab, java application, I'd prefer to have the main window following tiling, but to keep the figures that it generates not following it, to keep their sizes and desktop location, etc.

Their class name (of Matlab and figure windows) is identical so the only solution I found is to use the Ignored Window Captions setting, which is actually a great feature!

The only thing is that I need to specify each possible one independently, which is not so optimal: Figure 1, Figure 2, etc. That's why I thought of a better way to do this could be for instance using regular expressions, so I could say, apply that rule to all Window titles composed of "Figure" + white space + integer, relatively easily.

Not sure how hard this might be to implement, though.

**Comment by Jazqa** [comment]
While semi-easy within the code, I can't figure out a sane way to do this from the configuration interface. Best solution would be changing `Ignored Captions` from exact-match to substring-match, meaning that if you ignore "Figure" every program with the word "Figure" in the caption is ignored (f.ex. Spotify while listening to a song called "Figure"). 

While this sounds a little extreme, it doesn't interfere with regular use as much as you'd think. The caption-check is only done when a new window is added, so when you launch Spotify, it'll tile as the window caption is simply "Spotify". Problems show up when switching desktops and screens while listening to a song called "Figure" as desktop & screen switching happens by removing the window from the previous desktop/screen and adding it into the new one (thus doing the check again). If there are any other similarities within the window captions, you could ignore captions like "Matlab - Figure" etc. to avoid interferences with other programs.

EDIT: Now that I think of it, I should just modify the script so clients are only checked once and not every time a screen or desktop is changed. I'll see if I can implement this tonight.

**Comment by kupiqu** [comment]
Awesome!

**Comment by Jazqa** [comment]
Committed. It should work just like I described earlier. Window captions are only checked when the window is added for the first time, so desktop and screen switching should work as well.

**Comment by kupiqu** [comment]
Thank you!
