### ISSUE TITLE
The script does nothing at all

### ISSUE THREAD

**Issue by janbuchar** [Jazqa/kwin-quarter-tiling#29]
I installed the script from the AUR on Arch Linux (kwin 5.10.4), enabled it in system settings and rebooted, but it does nothing - windows appear just like they did before, keyboard shortcuts do nothing. I know it's impossible to tell what's happening from this - what other information can I provide you with?

**Comment by vegarab** [comment]
Is the script enabled under Window Management -> KWin Scripts -> Check Quarter Tiling and press enable. You can also try to restart the script with `kwin --replace` from anywhere.

**Comment by Jazqa** [comment]
I've probably messed up in the latest commit, what a perfect timing considering the Reddit post. I do try to test everything thoroughly but sometimes mistakes do happen. I'll start versioned releases soon to avoid this. I'll fix it the moment I get on my computer.

Did you just download it? How many displays are you using? Are you using Activities?

**Comment by janbuchar** [comment]
Yes, I downloaded it a couple of minutes before I opened this issue. I have a single display and I do use activities.

**Comment by Jazqa** [comment]
Activities should work. How many activities do you have? Are they empty or do they have windows open when you're starting the script? I'll try to replicate this and fix it. Shouldn't take long. 

I should probably mention that while activities work, pinning windows to multiple activities only tiles them on the first one. Supporting window pinning is possible but it's a huge job so I haven't implemented it yet.

**Comment by janbuchar** [comment]
I have 5 activities, some of them contained windows when I started the script. I also tried rebooting with the script already enabled. I do have some pinned windows, opening a mail client after a new mail notification appears is a huge pain without that.

**Comment by Jazqa** [comment]
I'm testing the script with eight activities and a ton of windows. Some of which are pinned to multiple activities and some of which are pinned to all activities. Surprisingly, the script is starting with no problem. If anything specific comes to mind, feel free to post here and it might help me reproduce the issue.

If you _really_ want to help. Type `wm console` into Krunner, copy the contents of `/usr/share/kwin/scripts/quarter-tiling/contents/code/main.js` into the console, execute the script and open a new window, console's output field should start filling up and the latest output should be some kind of error. Just paste the last few lines here and it'll help me figure it out.

If the error is similar to the error below, you need to select "Plasma" and then re-select "KWin" inside the console before pressing execute, it's a bug in the debugging console.

```
Error: ReferenceError: Can't find variable: readConfig at line 23

Backtrace:
<global>() at 23
```

**Comment by Jazqa** [comment]
Can you update and give it a shot? It's possible this was caused by the same bug that caused #28.

**Comment by janbuchar** [comment]
After the update, it seems to work. Thanks for your work!
