### ISSUE TITLE
keyboard shortcuts to move windows within a virtual desktop (single screen) stopped working

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#31]
I just realized that keyboard shortcuts to move windows within a virtual desktop (single screen) stopped working. Could you please check it out?

**Comment by eclipseo** [comment]
I can't reproduce this with the latest git, have you tried restarting kwin?

**Comment by kupiqu** [comment]
yes, I even rebooted the computer to be totally sure. wondering why you cannot reproduce... :/

just to be 100% sure, can you confirm that you are not moving the windows with the mouse but via keyboard shortcuts?

**Comment by eclipseo** [comment]
Yes, I set up my shortcuts as: (Meta key)+(C, T, S, R) for (Left, Down, Up, Right)

**Comment by kupiqu** [comment]
Ok, thank you.
I wonder if it may depend, then, on the settings of the script (?)

**Comment by Jazqa** [comment]
Unfortunately, I can't get on my computer until tomorrow. Should be a quick and easy fix though. If I had to guess, I've screwed something with the `Autosize` settings and @eclipseo has it enabled while @kupiqu has it disabled.

**Comment by kupiqu** [comment]
No problem! :)

However, I have the "Autosize" setting applied to "All Programs". For the case it may be useful, I have "Center: Tile".

**Comment by kupiqu** [comment]
A new reboot got this working again... May it be because of the recent package updates in KDE neon? Who knows, but it confirms this is not a fault of the script...

**Comment by Jazqa** [comment]
Oh, good. I was having some trouble with my computer and didn't even have the time to check it out yet :smile:
