### ISSUE TITLE
Panel overlaps windows

### ISSUE THREAD

**Issue by Tichy** [Jazqa/kwin-quarter-tiling#32]
I use this script in a single activity. When I switch to it just after the login, the panel always overlaps the windows. If I disable, then enable again this script, then it works normally.

Just after login
![screenshot_20170927_090158](https://user-images.githubusercontent.com/2348771/30900185-4aa69df4-a363-11e7-817b-31d22e3e64d1.png)

After reloading the script
![screenshot_20170927_090412](https://user-images.githubusercontent.com/2348771/30900194-5ade6436-a363-11e7-98ac-0748c3a47598.png)

**Comment by Jazqa** [comment]
I'm assuming the activity you boot into does not have that panel? This should be easy to fix as soon as I get on my computer. Meanwhile, there's a shortcut called `reset layout` in the keybindings, that should do the trick without restarting.

**Comment by Tichy** [comment]
They both have the same panel. Could it be because kwin_x11 is loaded before the panel and the tiling script "reads" the desktop size at that moment?

**Comment by Jazqa** [comment]
That used to be an issue back when I started writing the script but I thought I had it fixed. The script should read the desktop size when you open your first program. Are there any programs open when you login?

**Comment by Tichy** [comment]
Yes. Plasma always starts kontact and konversation from the saved session and kontact (at least, because konversation starts as minimized in the notification icon) appears before the desktop (and panel).

**Comment by Jazqa** [comment]
Great. I'm quite sure I can fix this as soon as I get on my computer. Thanks a ton for the help!

**Comment by Jazqa** [comment]
Should work now. If it doesn't, reply here and I'll fix it.

**Comment by Tichy** [comment]
Works perfectly :smile:
