### ISSUE TITLE
Maximizing windows breaks other ones (and probably script can stop also)

### ISSUE THREAD

**Issue by andreyorst** [Jazqa/kwin-quarter-tiling#35]
If a window is maximized, and then pulled down with mouse, its tile isn't set properly. Screencasts:
(warning: unexpected behavior intensifies)
[what_the.zip](https://github.com/Jazqa/kwin-quarter-tiling/files/1353684/what_the.zip)
[what_the2.zip](https://github.com/Jazqa/kwin-quarter-tiling/files/1353685/what_the2.zip) - in this one script stops, but when i reenable it, well you should see it with your own eyes.

---edit---
damn, my mouse pointer isn't recorded. Well most of actions are done with mouse

**Comment by Jazqa** [comment]
Apparently I broke this yesterday. I know exactly what's wrong. I'll fix it as soon as I get on my computer. I should avoid trying to fix stuff when I'm tired, whoops.

**Comment by Jazqa** [comment]
Ok, I fixed this but I have to leave the Autosize for tomorrow (I'm so tired I got '>' and '<' mixed up). Its current state is kind of embarrassing so I'll try to fix it as soon as I can tomorrow.
