### ISSUE TITLE
Quarter Move to next Screet not working

### ISSUE THREAD

**Issue by alothings** [Jazqa/kwin-quarter-tiling#38]
Hello,
The Global shortcuts for Quarter: Move to Next Screen and Quarter: Move to Previous Screen are not working in Manjaro KDE Plasma 5.9.
Tried different Global and Global Alternate keybindings including Meta+Shift+L and Meta+;
Issue encountered since installation, other shortcuts have worked fine.

**Comment by Jazqa** [comment]
Thanks for reporting the issue. This should be an easy fix, I'll fix it tonight when I get on my computer.

**Comment by Jazqa** [comment]
Curious. They are working for me. What kind of screen layout do you have? Are the resolutions different? Have you ignored a screen? A screenshot of your configuration would help me replicate the bug.

**Comment by daruuro** [comment]
Move to Next Screen and Move to Previous Screen aren't working for me as well. On KDE Neon 5.11, Plasma 5.11.3.
