### ISSUE TITLE
Allow flipping and rotating of layouts

### ISSUE THREAD

**Issue by ilevantis** [Jazqa/kwin-quarter-tiling#39]
The script is currently not very practical on screens with a vertical orientation as 2 windows will be tiled into long thin strips. To fix this it would be great to be able to rotate a layout so that the vertical split becomes horizontal.

Additionally, for cases with 3 windows on a horizontal screen, it would be nice to have the full height window on the right hand side instead of the left. Being able to flip or do a 180 rotation of the template would also enable this.

**Comment by Jazqa** [comment]
Current implementation of tiling is very inflexible indeed. I need to rework the tiling for my own sanity and for issues #10 and #30. When doing the rework, I will most likely add vertical layouts and layout rotation.

Unfortunately, it's a huge job and I'm currently very busy. I'll start doodling ideas of better ways to handle the tiling and once I've figured a sane way to do it, I'll get to the coding. Sadly, I can't say how long it'll take, but this is something that's in my head on a daily basis. 

Thanks for filing the issue though. New issues definitely help me avoid shooting myself in the foot again. First time around, I was designing a simple script for myself – I was extremely surprised and happy when people started to use the script. Now, thanks to the users, I've found a multiple use-cases I would have never thought of and I'll be able to take all of them into consideration when redesigning the tiling.
