### ISSUE TITLE
Maximizing windows shuffles window order

### ISSUE THREAD

**Issue by Crendgrim** [Jazqa/kwin-quarter-tiling#4]
When having four windows tiled on one screen and maximizing one of them, the other windows get re-tiled in the background. When unmaximizing the first window, the previous order does not get preserved. It would be nice if either the tiling left a gap, or the previous order was restored when unmaximizing the temporarily maximized window.

Given an initial configuration of four windows:
```
┌─┬─┐
│1│2│
├─┼─┤
│3│4│
└─┴─┘
```

I found the following behaviour to occur when maximizing / unmaximizing a given one of these windows, where the first configuration is after maximizing, and the second after unmaximizing.

```
   ┌─┬─┐  ┌─┬─┐
   │ │4│  │1│2│
1: │2├─┤  ├─┼─┤
   │ │3│  │3│4│
   └─┴─┘  └─┴─┘

   ┌─┬─┐  ┌─┬─┐
   │ │4│  │2│1│
2: │1├─┤  ├─┼─┤
   │ │3│  │3│4│
   └─┴─┘  └─┴─┘

   ┌─┬─┐  ┌─┬─┐
   │ │2│  │3│1│
3: │1├─┤  ├─┼─┤
   │ │4│  │4│2│
   └─┴─┘  └─┴─┘

   ┌─┬─┐  ┌─┬─┐
   │ │2│  │4│1│
4: │1├─┤  ├─┼─┤
   │ │3│  │3│2│
   └─┴─┘  └─┴─┘
```

This, while reproducable behaviour, feels quite random as a user. The only clear consistent behaviour is the previously maximized window moving to the top-left corner. I keep having to look around for where my other windows have moved to now.

**Comment by Jazqa** [comment]
It pushes the previously maximized window to the beginning of the array, moving the rest by one. I'm currently working on maximized (and minimized) windows saving their position and returning to their old positions when unmaximized.

**Comment by Jazqa** [comment]
Done. Both minimized and maximized windows remember their positions.

**Comment by Crendgrim** [comment]
Thank you! :)

**Comment by kupiqu** [comment]
I realized that if 2 windows are present and 2 others are minimized, then launching a 5th makes it appear in a different desktop.

I wonder whether this is intended behavior... If it is not, I guessed this might be a side effect related to the changes introduced in this issue...

**Comment by Jazqa** [comment]
Intended. Minimized, maximized and fullscreened clients "reserve" their spot on the desktop they were minimized, maximized or fullscreened on. If you close the minimized client, a new window will have space on the desktop.
