### ISSUE TITLE
Toggle tiling for current desktop doesn't restore windows size/positions anymore

### ISSUE THREAD

**Issue by alxlg** [Jazqa/kwin-quarter-tiling#40]
Time ago when I used Esc + Meta shotcut the tiling was toggle for current desktop and the tiled windows went back in their positions and sizes. Now it doesn't happen anymore, the windows remain in the position and size they were when tiled but they are not tiled anymore.
You can see the previous behavior here:

![[](https://gfycat.com/gifs/detail/CoordinatedBountifulBeaver)](https://thumbs.gfycat.com/CoordinatedBountifulBeaver-size_restricted.gif)
[link](https://gfycat.com/gifs/detail/CoordinatedBountifulBeaver)

### steps to reproduce:
* press Esc + Meta and check the windows are not tiled anymore, but they still have size and position they had when tiled.

**Comment by Jazqa** [comment]
I've intentionally changed the behavior to avoid manually resizing the windows when a desktop is ignored. Glad you liked the old behavior though, I'll definitely bring it back as an option!

**Comment by alxlg** [comment]
Thank you very much!

**Comment by alxlg** [comment]
Hi, any news?

**Comment by Jazqa** [comment]
Thanks for the reminder. I haven't been around my computer much, but because of the Holidays, I'll have a few hours tomorrow. I'll reply to this thread after I've fixed it. Sorry for the delay.

**Comment by alxlg** [comment]
No problem, thank you!

**Comment by Jazqa** [comment]
My apologies once again, I couldn't get a VM running on my laptop during the holidays. Anyways, I'm home now and ready to fix this on my main rig. Do you want the previous behavior or would you prefer if the Windows' sizes and positions are actually reset to their original locations? The previous behavior centers the windows

**Comment by alxlg** [comment]
Hi, no problem take your time! I think resetting to original locations would be better, what do you think?

**Comment by Jazqa** [comment]
I've partially re-implemented this with #53. If you define **Float Width** and **Float Height** (to 1-100 as in percentage of the screen estate) from the configuration interface, removed windows get reset to the set percentage and centered, just like in the link.

Not going to close the issue yet as I'll still have to improve the feature, add a checkbox to enable/disable the feature and store the original locations.

**Comment by alxlg** [comment]
Thank you, it works fine but I had to relogin in the session, because setting them to 50 or 100 makes Quarter Tiling not working at all. Logout and login again fixed it.
