### ISSUE TITLE
Changing multi-monitor configuration stops script

### ISSUE THREAD

**Issue by hpaantee** [Jazqa/kwin-quarter-tiling#42]
I use a notebook with an external monitor. The script works perfectly fine if i use them, unless I for example use xrandr to deactivate the notebook-monitor. Then the script stops working and I have to go to "kwin-scripts", deactivate quarter-tiling, and then activate it again. 
Or is there an easy cli command to restart your script?

**Comment by Jazqa** [comment]
This is a bug I've been meaning to fix for a long while, but I've had problems maintaining the window layout after restarting the script. I personally restart the script with by typing `kwin --replace` inside Krunner, but it should work from terminal as well.

**Comment by jarlucmat** [comment]
The problem with this solution is that all windows are displaced across all activities

**Comment by Jazqa** [comment]
If I had to guess, all the activities get new identifiers when KWin is restarted. Activities are such a pain to deal with.

**Comment by jarlucmat** [comment]
How does the script handle windows that are on multiple activities?

**Comment by Jazqa** [comment]
Awfully. I patched activities after I had already created the script. Windows are tiled according to the first activity on their list. If activity of a window is changed, it's removed from tiling until added again. A full activity support would require constant iteration through the activity list.

**Comment by ilkerhk** [comment]
Exact issue happens on my configuration. I don't use activities but only virtual desktops. On hdmi connect or disconnect system hangs until I restart kwin_x11.  

I am ok with restarting kwin_x11 every connect/disconnect, however, all window positions mess up. 
A workaround is to disable quarter tiling; restart kwin; then enable quarter tiling. 
In that case window positions does not change.

Is there a way to disable quarter-tiling (or any kwin-script) from command line? 
 Maybe  hpaantee  was also asking this...

best,

**Comment by Jazqa** [comment]
This is still a little iffy (requires a window movement for them to tile again), but it should at least work now.
