### ISSUE TITLE
Conflict with plasma-applet-active-window-control

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#44]
I noticed that there is a conflict between this script and plasma-applet-active-window-control when using the option "hide titlebar for maximized windows".

To reproduce it:

- maximize a window -> titlebar should be gone
- minimize the window (e.g., by using buttons in plasma-applet-active-window-control)
- restore the window (e.g. from the task bar)

expected behavior is that the window would come back to be maximized without the titlebar

however, when using the tiling script, the window is restored to a tile

this would not be a problem (I actually like the tiling better than to restore to the maximized window) if the window would recover the titlebar, which is not the case

is there a way to retore maximized windows from minimization to a tile, while getting back the titlebar at the same time?

Currently, to get back the titlebar, I have to go to buttons of plasma-applet-active-window-control and restore from maximization, even if the window is not maximized anymore.

**Comment by Jazqa** [comment]
If I had to guess, the same happens with fullscreen clients even without the extension. Minimizing and then restoring a client is probably not checking if the restored client is maximized/fullscreen. Should be a simple fix, I'll give it a try as soon as I get home.

>is there a way to retore maximized windows from minimization to a tile, while getting back the titlebar at the same time?

I'm afraid not. I can not maximize or unmaximize a window via the script. Hell, the script can't even know whether a window is maximized or not without comparing its size to the available screen size (see #17). Maximized windows is one of the biggest issues I've had with the script.

**Comment by kupiqu** [comment]
> Should be a simple fix, I'll give it a try as soon as I get home.

Thank you

**Comment by Jazqa** [comment]
Wow, I didn't even need to get home to fix this. Look at this [sick commit](https://github.com/Jazqa/kwin-quarter-tiling/commit/617da79564433042080d6c2c76edf612eb3f1f53). All I needed to do was add a word. I don't actually use Active Window Controls but the issue existed even without it, so hopefully it's working for you now as well.

Once again, thanks for reporting the bug, you've been a huge help since the beginning of the script!

**Comment by kupiqu** [comment]
Awesome, many thanks!
