### ISSUE TITLE
Tiling creates new desktop instead of opening on previous desktop

### ISSUE THREAD

**Issue by ghost** [Jazqa/kwin-quarter-tiling#45]
This is on a fresh installation of ArchLinux with KDE (Latest). When opening an app, it will open on Desktop 2 and swap to that by default. Upon closing all the windows, there are 3 - 4 open desktops setup which then need to be removed.

I've attempted purging and re-installing but it continues. Unsure if the latest versions of KDE are causing conflicts? I'm new to this Kwin stuff so please let me know any logs that you require.

Love your work, thanks.

**Comment by Jazqa** [comment]
Automatic desktop removal is something I have not been able to do in the past (it works fine, but crashes Plasma). I should give it another try with the new version. Anyways, is your first desktop completely empty? Maximized and fullscreen windows "block" an desktop, forcing new windows into a new desktop.

**Comment by ghost** [comment]
Hey Jazqa.

Yes. I've since re-installed and it seems to not happen "as often" but I notice that I open a new application and it opens on another screen instead of Tiling. I then force tile with Super + F x2 and it then has the first desktop blank. Not a huge issue, but just noticing that it's not as consistent as it used to be (unsure if that is the scale of the plugin, or if it is KWin causing the issues though.
