### ISSUE TITLE
the script does not respect kwin geometry rules

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#46]
I want konsole to occupy 1 quarter horizontally and 1 or 2 quarters vertically. I tried to use kwin geometry for this forcing a maximum size that was exactly 1 quarter horizontally and 2 quarters vertically, but the script doesn't seem to respect it, so when konsole is the only window it utilizes the whole available space.

Do you think this could be fix somehow? Thank you!

**Comment by Jazqa** [comment]
Adding Konsole to "Small Programs" is the closest you're going to get with the current version. I don't think I'll be able to respect the "Maximum Sizes" without using the "Small Programs", but adding a new option for programs to never be either wider or taller than a quarter could be possible. I've also thought about adding similar "Minimum Sizes" feature, where chosen programs would always occupy half of the screen.

**Comment by kupiqu** [comment]
Yes, I actually had Konsole in Small programs, but thought that I'd like to let it grow vertically, so that's why...

If you would add these options for Small programs, it would be great!

**Comment by Jazqa** [comment]
Unfortunately I can not respect KWin rules and tile a window, a window is either tiled with the script rules or floating with KWin rules.
