### ISSUE TITLE
Quarter Tile unexpectedly tiles my desktop/background

### ISSUE THREAD

**Issue by ysndr** [Jazqa/kwin-quarter-tiling#47]
Hey,

recently I experience a weird issue with this tool.
Whenever I use "Quarter: Move <direction>" on the desktop the background gets _tiled_ somehow as can be seen on the next picture.
I would expect that __nothing__ would happen if I had an empty screen as `plasmashell` is disabled from beeing tempered with by source...

![screenshot_20171202_221339](https://user-images.githubusercontent.com/7040031/33519825-2e88d440-d7af-11e7-8e6f-f077d3b684f2.png)

Has anybody an idea why this might happen and how to fix this. 

cheers

**Comment by Jazqa** [comment]
I've fixed this now.

It happened because floating windows can be tiled with the `Move` shortcuts. When implementing the feature, I had been careless and made all windows (including desktop) tileable.

**Comment by ysndr** [comment]
Perfect, thank you for the effort
