### ISSUE TITLE
IDE causes problems

### ISSUE THREAD

**Issue by huti26** [Jazqa/kwin-quarter-tiling#48]
Hey,
I only tried it with IntelliJ, but I am pretty sure that the following problem is going to appear on many IDEs.

When you start IntelliJ you first have a small window, where you can pick, which project you want to start. The tiling script cant change the size of this window, but it positions it in the correct tile. Now when you choose a project, the small window closes and the actual IDE starts. So there are a couple of split seconds, in which you dont have any window open. When you want to have IntelliJ open on its workspace in full size, this will result in the following:

you pick a project -> the small window closes -> the tiling script notices that you are on an empty workspace, so it moves you back on another workspace -> IntelliJ opens on the new workspace instead of the one, where it was actually started

So my question is, is there any way to disable the function, which automatically moves back to a non empty workspace?

**Comment by Jazqa** [comment]
Sorry, I had forgotten about this, but got a reminder now that you closed it. Did this solve itself? It's not only the IDEs, but most programs that flash a window before starting the actual program.

>So my question is, is there any way to disable the function, which automatically moves back to a non empty workspace?

I should add three options for disabling automatic movement (previous, forward or both). Besides these issues, I know some people don't like being automatically moved across workspaces.

**Comment by huti26** [comment]
I found another tiling script, which is more basic than yours and Im currently trying that now. 

If you are interrested: It has exactly the same problems as yours with little popup windows. Actually for IntelliJ its even worse, because it sometimes ends up completly crashing the programm. Only advantage the other one has, is that you dont get moved at all.
