### ISSUE TITLE
feature request: extra ignored programs category that keeps the logic of locations in quarters but ignores resizing

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#5]
I wonder whether you would consider an additional ignored programs category in settings for applications that would obey tiling in terms of location but without being resized.

I am thinking about applications that appear better if they are narrower than even a quarter of the screen (and much better than in fullscreen) as for instance: choqok, telegram, whatsie, kopete... You get the idea...

This way they would appear nicely while they would still keep the logic of tiling applications in quarters, etc.

In terms of location I guess these applications would looked better if centered with respect to the available space.

I hope I was clear enough, and thanks for considering!

By the way, I started using tiling thanks to your kwin script!! I tried others before but they didn't convince me to stay more than for testing.

**Comment by Jazqa** [comment]
This will be fun and depending on the approach, difficult to implement. I will definitely work on this but it might take a while longer than the usual feature requests.

I've tried the opposite before (large programs, such as Gimp, automatically taking more space), but I actually liked the freedom of shrinking some windows beyond their limits (afterall, they could be enlargened at will). I had never thought of the smaller programs, but I agree, they look absolutely hideous if stretched beyond limits. Thanks a ton for the suggestion!

**Comment by Jazqa** [comment]
Something like [this](https://gfycat.com/AfraidEarnestIrishsetter)?

**Comment by kupiqu** [comment]
Awesome!

**Comment by Jazqa** [comment]
A few finishing touches and I'll push it. I think I'll just add a category for "non-resizeable clients". If you scale the windows over the limits, they will overlap but the tiling will stay intact. If you scale the window within the empty space, it will not affect the other windows. Video incoming.

Edit: Misclicked the close, whoops.

**Comment by Jazqa** [comment]
Okay, allowing the "small" client to over-tile is the easiest (and the most stable) solution. If you use the feature for small programs, over-tiling should never be an issue. Video [here](https://gfycat.com/IckyTatteredJackal). I'll create the configuration interface and push the change.

Edit: Nevermind, I'm too much of a perfectionist and it's not that difficult. I'll just block resizing if it gets bigger than the available tile. However, I'll leave it for later.

**Comment by kupiqu** [comment]
Looks great, thank you!
I agree this is supposed to be applied only to "small" clients so over-tiling should never be an issue.

**Comment by Jazqa** [comment]
Ok, try it out and tell me how it works. I couldn't use any of the programs you mentioned as they all required registration. I'll close the issue once I've refined the feature so if you try to resize a window further than the free tile allows, the other windows adjust and do not overlap. Might have to wait until tomorrow though.

Protip: If you can't figure out the window class of a program, you can detect it via KWin's "Window Rules".

**Comment by kupiqu** [comment]
Works great for choqok and whatsie, thank you!!

Unfortunately telegram (telegramdesktop for kwin) does not allow to decrease the vertical space enough to fit vertically in a quarter of the screen, so it overtiles vertically. 

I guess there is no way in kwin to force telegram to use less vertical space :/

Can you think of a workaround for situations like this, perhaps adjusting the vertical size of the complementary app?

**Comment by kupiqu** [comment]
Also, one thing that could be refined to optimize tiling space refers to when there are 3 apps present. The idea would be to control that the one that occupies half of the screen is not a "small client" (unless all 3 are small clients), so all that space is occupied :)

**Comment by Jazqa** [comment]
Yep. That's exactly what I'm going to do. Until then, you'll have to manually decrease the size of the overlapping window. Shouldn't take too long to fix though.

Edit: The other idea is great too. None of this should be too difficult. I'll just have to run some errands before I can start fixing things ;)

Edit 2: Plan is to make use of all the available space. Once I'm done with this the small windows will not take up a whole quarter or half (if it's the only client, it will be placed in the middle like it is now), but the other windows will adjust and come as close to them as possible. I'll also pile the small windows to the same category with the large ones so if a huge window is listed under the category (small windows [will change the name]), other clients will make space for it when it's added.

**Comment by kupiqu** [comment]
Oh, actually I can use a kwin rule to force telegram to occupy less vertical space!

Edit: Yet, implementing the 'fix' will be great for users that do not master kwin rules or prefer to have more vertical space...

**Comment by kupiqu** [comment]
> Edit: The other idea is great too. None of this should be too difficult. I'll just have to run some errands before I can start fixing things ;)

Excellent!! No hurries :)

**Comment by Jazqa** [comment]
[Progress](https://gfycat.com/SparklingCoordinatedGrison). I think tiling the smaller windows closer to the center of the screen looks & feels better. Now I'll just need to figure out a solution for the following issue
> Unfortunately telegram (telegramdesktop for kwin) does not allow to decrease the vertical space enough to fit vertically in a quarter of the screen, so it overtiles vertically.

I also tried this,
>Also, one thing that could be refined to optimize tiling space refers to when there are 3 apps present. The idea would be to control that the one that occupies half of the screen is not a "small client" (unless all 3 are small clients), so all that space is occupied :)

but having the windows automatically switch places like that felt a little confusing so I think I'll just skip this part, sorry.

**Comment by kupiqu** [comment]
> Progress. I think tiling the smaller windows closer to the center of the screen looks & feels better. Now I'll just need to figure out a solution for the following issue

Looks nice! Would it work automatically also if the inital size of a small client overtiles?

> but having the windows automatically switch places like that felt a little confusing so I think I'll just skip this part, sorry.

I understand. Perhaps this could be set as an option, disabled by default, for the users that want to give this a try (?) 

But yes, I didn't try myself, perhaps this feels as weird to me as it feels to you... maybe I could experience it by myself if you would put the code in a different branch (?)

Thanks for your great work! and sorry to botter you with this!

**Comment by Jazqa** [comment]
You are not bothering at all, I actually enjoy this. I'll fix the remaining bugs and push it in a hour or two. I'll probably add the other feature as an option as well.

Edit: Sorry it's taking a while. I keep running into the weirdest issues.
Edit 2: Found the reason for most of the issues, multi-screen environments are evil.'
Edit 3: Almost there..!!

**Comment by Jazqa** [comment]
What a job. Didn't add the option yet as I bundled large and small clients together. Clients listed under "Small Programs" (will change the name soon) respect their initial size and make other windows adjust to them. If you want a large program to always be larger than a quarter tile, that program should also be added to the "Small Programs" category. ((f.ex. Telegram is a "large program" vertically and a "small program" horizontally, which makes dividing "small" and "large" programs extremely difficult.))

Still a lot to do (moving & resizing these windows), but in its current state, it should work better than the last commit did. Try it out and give me some feedback. I don't use such programs myself but I tried to test it thoroughly and in my opinion, the feature felt logical and intuitive.

**Comment by kupiqu** [comment]
It works nice!

For whatever reason small clients are not centered horizontally anymore once 2 or more windows are present, is this expected?

That's the only thing I found, besides what you mentioned about moving windows...

**Comment by Jazqa** [comment]
Assuming you speak of the issue visible in the picture below, it's not intentional. I'll commit the fix tomorrow with movement & resizing improvements. Thanks for all the help and ideas, I'm having a ton of fun with this.

![Issue](http://i.imgur.com/z9pwJmh.png)

**Comment by kupiqu** [comment]
Excellent, thanks!

**Comment by kupiqu** [comment]
I think this issue could be set as closed - fixed (the extra category has been created), and then we could perhaps open two other more specific issues for:

- Option to optimize screen space by moving small clients around (like for instance putting them in quarters instead of half screen, or adding them together to a quarter if they would fit)
- Issue about small clients not being horizontally centered when >=2 windows are present

Should we do that?

**Comment by Jazqa** [comment]
>Option to optimize screen space by moving small clients around (like for instance putting them in quarters instead of half screen, or adding them together to a quarter if they would fit)

Deifnitely. Let's open an issue for this.

>Issue about small clients not being horizontally centered when >=2 windows are present

This is actually intentional this time and helps optimizing available screen space. I'll try to demonstrate with videos. 

[Two small clients, centered vertically & horizontally](https://gfycat.com/IgnorantFoolhardyBuck)

[Normal clients (firefox & dolphin) and small clients (feh & konsole). Small clients' tiles are shrunk to use all of the vertical space available](https://gfycat.com/DeafeningAgileAfricanharrierhawk)

**Comment by kupiqu** [comment]
> Deifnitely. Let's open an issue for this.

Done

> This is actually intentional this time and helps optimizing available screen space. I'll try to demonstrate with videos.

I'm not quite following. Let's take the first video as a reference. Couldn't we have this very same behavior applied to the horizontal axis (as it is shown in the video for the vertical axis)?

In the video, apps are centered vertically and they move according to new windows appearing. Couldn't we repeat it horizontally as well?

Asking because I think windows look much better when centered...

**Comment by Jazqa** [comment]
>I'm not quite following. Let's take the first video as a reference. Couldn't we have this very same behaviour applied to the horizontal axis (as it is shown in the video for the vertical axis)?

Yes. I'll add this tonight. I'll have to experiment with it a little to avoid the issue demonstrated in [this video](https://gfycat.com/WickedEqualChameleon) (Atom shrinking), but it's at the top of my to-do list. The whole small/large clients feature took a surprising amount of work, but now that the basics are somewhat working, I'll keep polishing it until everyone is satisfied. I really enjoy working on this.

**Comment by kupiqu** [comment]
> I'm not quite following. Let's take the first video as a reference. Couldn't we have this very same behavior applied to the horizontal axis (as it is shown in the video for the vertical axis)?
> In the video, apps are centered vertically and they move according to new windows appearing. Couldn't we repeat it horizontally as well?

Sorry, I got confused by the video above (Two small clients, centered vertically & horizontally), so please ignore my previous comments.

However, aesthetically I still prefer the previous behavior when windows were centered in the respective quarters (assumed >=2 windows are present).

Do you think this could be, perhaps, set as an option?

**Comment by Jazqa** [comment]
>However, aesthetically I still prefer the previous behavior when windows were centered in the respective quarters (assumed >=2 windows are present).

>Do you think this could be, perhaps, set as an option?

Sure thing. Will have to wait for tonight or tomorrow morning but adding an option "Center According to: Screen/Tile" is a great idea!

**Comment by kupiqu** [comment]
Excellent, thanks!!

**Comment by kupiqu** [comment]
I found an issue regarding small clients (if you want I can open another issue, but it's perhaps not necessary), when two of them have different preconfigured sizes and appear in a same column. 

The issue only happens when the smaller client is open first, in that case the other bigger client, when opened second, is resized to the size of the first, instead of following its own rule size.

I hope I was clear enough :)

**Comment by Jazqa** [comment]
>I hope I was clear enough :)

Considering the fact I managed to locate the bug on my phone, I'd say so. I'll fix it as soon as I can get on a computer (~20 hours)!

**Comment by kupiqu** [comment]
You fixed it, thank you!
