### ISSUE TITLE
Tile 3 windows

### ISSUE THREAD

**Issue by ilkerhk** [Jazqa/kwin-quarter-tiling#51]
thanks for this nice script. 
Is there a way to tile only 3 windows and float the rest?

**Comment by Jazqa** [comment]
Unfortunately, the script doesn't currently support layouts with three windows. I've wanted to add more layouts but I've been way too busy.

**Comment by Jazqa** [comment]
This is will be possible soon. I'm completely rewriting the script and this feature is already available in the `rework` branch. The rework branch is a lackluster in many ways, but if all you want is tile three windows and float the rest, it should do just fine.
