### ISSUE TITLE
Save the layouts feature

### ISSUE THREAD

**Issue by DaBlitzStein** [Jazqa/kwin-quarter-tiling#52]
I think it is very interesting a new feat to save the layouts and the window name reference. Then you load the layout and all the apps are executed. Like terminator or such.

Thank you.

**Comment by Jazqa** [comment]
This would be a great feature indeed. Shame such a function cannot be implemented because, as far as I know, executing programs via the KWin API is not possible and neither is saving any data (such as layouts).

**Comment by Jazqa** [comment]
Closing because this is, unfortunately, not possible with the current KWin API.

**Comment by jcrben** [comment]
Has this ever been reported upstream as a feature request? If not, I'm interested in making the request but you might have a better idea of how to phrase it.

Looks like there are a lot of components - https://bugs.kde.org/describecomponents.cgi?product=kwin - I glanced at [scripting](https://bugs.kde.org/buglist.cgi?component=scripting&list_id=1496044&product=kwin&resolution=---), [effects-window-management](https://bugs.kde.org/buglist.cgi?component=effects-window-management&list_id=1496043&product=kwin&resolution=---), and [core](https://bugs.kde.org/buglist.cgi?component=core&list_id=1496042&product=kwin&resolution=---). There's also a [tiling](https://bugs.kde.org/buglist.cgi?component=tiling&list_id=1496045&product=kwin&resolution=---) component with no open bugs (looks like bugs stopped in 2013).

**Comment by Jazqa** [comment]
@jcrben, KWin scripts can utilize QML. While this feature can't be implemented with KWin scripting API, it might be possible with QML. I need to get a little more familiar with QML before I can say anything for sure though.
