### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by Jazqa** [Jazqa/kwin-quarter-tiling#59]
I'm rewriting the script from scratch. If you want to test it - use the `javascript_rework` branch. Any ideas, suggestions and feature requests welcome in this thread.

**Comment by Crendgrim** [comment]
If possible, I would still like to see the ability to lock certain programs/windows to a given size, for example:
- Force Firefox to always take at least half a screen and not get reduced to a quarter.
- Have an IDE set to always take up its own full desktop, inhibiting any other windows opening on the same desktop/screen, while still having the same margins as other windows.

I'd especially like the second option. Scrolling on the bottom of the screen to switch desktops is a very nice thing, and currently I have to maximize my IDE to prevent that screen/desktop from taking newly opened windows (see #26 where we discussed this previously).

**Comment by Jazqa** [comment]
@Crendgrim, I am going to add multiple new layouts - many of which will include a "master" window filling up half of the screen ([examples](https://imgur.com/a/eR48Q)). Program-specific behavior is a huge pain in the ass and really grows up the code-base, but I might add two new program-list settings -  one for preferred "master" programs taking half of the screen and one for "super" programs hogging up a whole desktop. 

Also, am I in the past or are you in the future?
![https://i.imgur.com/jtJ3Jcq.png](https://i.imgur.com/jtJ3Jcq.png)

**Comment by barisdemirdelen** [comment]
Looks good man, can you post here when it is semi working? I would like to test it as well.

**Comment by 3ximus** [comment]
NIce! Make a checkbox on your original comment with the stuff that you plan to / or already implemented.

**Comment by Jazqa** [comment]
It's under the `rework` branch and it's using Qml to include multiple files. The basics are somewhat working now (moving, resizing etc.), but I've got a ton of annoying stuff left (e.g. minimizing & maximizing). I'm going to make the script less intrusive and more stable by reducing the features. I'm probably giving up Activity support (Activities wouldn't crash, but only one Activity gets tiled), automatic desktop switching (it was a little intrusive) and automatic resizing/small clients (literally the worst part of the current code, a ton of `if` statements and `switch` cases piled on top of each other). 

I might implement some of the removed features later, but I'll start without them to keep things simple and stable.

![https://i.imgur.com/CGdtovB.png](https://i.imgur.com/CGdtovB.png)

**Comment by Crendgrim** [comment]
If you remove automatic desktop switching, what happens when you open a window when the current desktop is full?

**Comment by Jazqa** [comment]
@Crendgrim, the next one would float. I'm probably adding automatic desktop creation/switching for new windows as an option as it's quite simple. Automatic removal/switching for closed windows is prone to bugs and crashing though.

**Comment by Crendgrim** [comment]
That sounds good to me, I'd love to keep that option.

**Comment by v3ss0n** [comment]
Looks really good , there is kwin-tiling project too  :  https://github.com/faho/kwin-tiling

**Comment by FrauH0lle** [comment]
@Jazqa Regarding the activities: Would it be possible to add their support experimentally? I use them quite a lot and so far, I had never issues with your script. Maybe a checkbox with a warning which enables that feature and has a warning in the tooltip?

**Comment by Plonq** [comment]
I think I use tiling different than what this script assumes. I set initial desktops to 10, and use it more like a tiling WM like i3. I.e. I switch to a desktop, then open the apps I want on that desktop. Therefore I have empty desktops in the middle usually.

Currently the script breaks if I move windows between desktops. Either dragging, or with a shortcut. I'm guessing this isn't typical use.

Thought I'd mention this since you're doing a re-write.

**Comment by Jazqa** [comment]
@Plonq, that's something I'm going to take into consideration when rewriting the script. I'm getting rid of the automatic desktop switches (probably adding it as an option, off by default) and making it more adjustable to different use cases.

**Comment by Plonq** [comment]
@Jazqa Awesome! And thanks for the script!

**Comment by Coolaswa** [comment]
What is the reason you mentioned giving up activities support? Is it that much of a workload to maintain?

**Comment by Jazqa** [comment]
@Coolaswa, current solution is not too much trouble but very buggy. A perfect solution might not be possible and a decent one would require constant iteration through all the activities making the script way slower. Maybe I can figure something out by always prioritizing the current activity. I've been quite busy so  I haven't been able to continue the rewrite for a while.

**Comment by barisdemirdelen** [comment]
@Jazqa,  just a heads up.

I tried the rewrite branch a little while ago. It didn't work for me at all at the start. But i liked the structured code much more than the current one, so i made it work for my general usage. In the process i reformatted/restructured code a little bit too much so i am very reluctant to send a pull request. I believe i fixed most of the bugs i have been experiencing though. I'm currently using it daily.

If you want to have a look at my branch or want a more structured pull request, feel free to poke me.

**Comment by Jazqa** [comment]
@barisdemirdelen, I'll give it a peek as soon as I can. Master is a mess as it's some of my first code, but hopefully I'm able to keep the rewrite way cleaner.

As a completely unrelated It's been quite a while since my latest commit as I'm getting a new computer and had to return three already. I also need to get a new monitor to develop the script as I currently have a single one.

**Comment by alxlg** [comment]
Hi all, I have an idea to enable multiple layouts in an intuitive way (but I know implementation could be very difficult). The easier way to try what I mean is to install Inkscape and enable many modules in the sidebar, you can drag each module and tile it in different positions. In this image you can see 5 modules tiled in a custom layout by simply dragging them:
![screenshot_20180403_121025](https://user-images.githubusercontent.com/26327475/38243497-ff81af08-3737-11e8-948a-7c3f524bd28c.png)

**Comment by eclipseo** [comment]
@Jazqa Any chance you find time to work on the rewrite?

**Comment by Jazqa** [comment]
@eclipseo, I've been switching hardware quite often lately and haven't had a stable KDE environment for a while. I just got a new machine with Kubuntu 18.04 installed today and might start working on this again now.

**Comment by Jazqa** [comment]
In case anyone cares - I moved this to a branch called `javascript_rework` and started from scratch once again. I may strip multiple features in order to squash most of the bugs, but since I just started rewriting the script I'm not sure which ones will be left out. Looks like Activity support is going to stay thanks to the recent changes described below.

Most notable difference in the new script is the way Screens, Desktops and Activities are handled. Instead of creating a new Array for each (ending up with a three dimensional Array `tiles[activity][desktop][screen]`) I'm storing all clients inside a single Array and simply filtering them by the current Activity, Desktop and Screen. This alone will fix a ton of issues with the current `master`, possibly affecting the performance. My current setup runs KDE very poorly and I seem to have decent performance at the moment though.

Also, major difficulty in the development: I only own a single monitor. Making multi-monitor support kind of difficult to implement. I'll see if I can grab an old TV or something for this though.

**Comment by kupiqu** [comment]
Interesting! 

what is the status? should we test it or wait a bit?

**Comment by Jazqa** [comment]
@kupiqu, I'd still wait. I just started from scratch again. After a super busy year I finally have some time to work on this and I'll probably be updating the project daily. I'm implementing all the basic functionality first - leaving all the usability stuff like multiple layouts, keybindings and settings UI for later.

I'm also aiming to create much cleaner and easily maintainable solution, leaving multiple features out. Earlier I really screwed things up by trying to include features I should have just left out of scope. I'll most likely clean most of the issues as soon as I get the new branch to master.

**Comment by Jazqa** [comment]
[Some progress webms in case anyone is interested.](https://imgur.com/a/zR24F1X) Unfortunately, KWin runs like crap on my machine even without any adjustments, so it's very hard for me to tell how's the performance.

**Comment by kupiqu** [comment]
It looks good!

**Comment by FrauH0lle** [comment]
Hey @Jazqa ,

are you still working on the script/rewrite? 
Would be quite a pitty if this project dies slowly as it is still the only one among the three kwin tiling extensions (https://github.com/faho/kwin-tiling & https://github.com/lingtjien/Grid-Tiling-Kwin/tree/master) that does work properly with multiple monitors and activities.

**Comment by Jazqa** [comment]
@DonHugo69 I am. I know it has had long periods of inactivity, but I've just been unfortunately busy lately. I'm not starting any personal projects until I'm personally pleased with this one and at the moment, I definitely am not.

That being said, the rewrite started well and I have most of the basic functionality in place. I completely changed the way the script works and the new version will support multiple monitors and activities way better than the last one. 

I still have to figure out which layouts I'm going to support and implement the tiling logic. I do want to support moving and resizing windows with mouse in every layout and I want to implement at least one layout that supports endless amount of windows.

**Comment by FrauH0lle** [comment]
@Jazqa That's great to hear! Thank you for your response!

**Comment by lilianchiassai** [comment]
@Jazqa Are you still working on this script? I would like to disable the desktop opening automatically and I'm willing to give a hand, but I can't find a proper documentation on how to develop/debug kwin scripts.

**Comment by Jazqa** [comment]
I've been tired and busy, but I've finally found time to continue the rewrite. I think it's the fourth time I start from scratch, but at least this time around I'm making quick progress and enjoying the development. I'm currently rewriting the script in modern TypeScript and it's making my life way easier. Changes are happening on the `typescript-rework` branch which should already have the most basic functionality with more being implemented each day.


-------------



**Update 1**: Basic functionality and keybindings have been implemented, but I've hit a wall with dynamic desktops. Adjusting the amount of desktops via the script is currently very unstable, and I'll have to figure out a way to do it smoothly. 

Activies are also a work in progress, and while the rework already has partial support for them, I don't know if supporting them completely will be worth the effort. As of now, all of the windows in the current activity will be properly tiled, but resizing them will also affect the layouts on other activities.


**Update 2**: Virtual desktops are killing me. Adjusting them seems very unstable on Ubuntu 18.04.

**Comment by alxlg** [comment]
@Jazqa to manage desktops I use Virtual Desktop Bar: https://store.kde.org/p/1315319/ that adds/removes desktops automatically and seems pretty stable to me.

As for Activities, personally it is important to keep the current behavior for me, including the per-Activity disabled tiling.

**Comment by Jazqa** [comment]
@alxlg, thanks, I'll take a look into it as soon as I can. Once I get the dynamic desktops working, there shouldn't be many challenges left with the rewrite.

Ignoring an activity will definitely be possible, but activities may not have "unique" tiling – meaning that if something is resized on "Activity 0", the layout may also change on "Activity 1". Unique tiling should be possible, but it would make the script a lot heavier.

**Comment by Jazqa** [comment]
I'm giving up on dynamic desktops. The script will automatically switch between existing desktops if "Automatically change desktops" is enabled, but it will not create nor remove desktops. I did get both, creating and removing, working with different approaches, but unfortunately all of them felt extremely unstable.

@alxlg, Virtual Desktop Bar is amazing, but it's using the C++ API instead of the Javascript API, which means I can't do all the things it does without rewriting the script in C++. I've tried multiple approaches, including some ideas from Virtual Desktop Bar and [kwin-dynamic-virtual-desktops](https://github.com/rliang/kwin-dynamic-virtual-desktops), but KWin still tends to crash around 10% of the time when creating or removing desktops (Kubuntu 18.04).

**Comment by alxlg** [comment]
@Jazqa I would leave the dynamic desktops functionality to Virtual Desktop Bar, maybe just suggest users to use it in combo with your script?

**Comment by Jazqa** [comment]
The new version feels extremely stable. Even though I’ve removed some features and simplified the script, the new version is more enjoyable in day-to-day use and doesn’t interfere with basic workflow as much as the old one. I might merge the new version into master this week.
