### ISSUE TITLE
Wine and Steam being added to the ignore list has no effect

### ISSUE THREAD

**Issue by maxigaz** [Jazqa/kwin-quarter-tiling#6]
In the settings of the KWin script, Wine is added by default, but applications run through Wine are still tiled. It's the same with Steam.

An example is the game Thief 2, run either with `wine Thief2.exe` or through Q4Wine. In this case, I tried making it float with Meta+F as a workaround (so that it runs fullscreen, as it should, rather than tiled), but then I still have to press Alt+Tab a few times to really make it fullscreen. Also, after that, the script stops working altogether and I need to disable and enable it again in the KWin Scripts dialogue.

**Comment by Jazqa** [comment]
The default ignore list is not very comprehensive as I can't personally use all the software in the world. You can find the exact program names via "Window Rules" > "New" > "Detect Window Properties" and add them to ignore list. 

I'd be delighted if people kept reporting the programs that don't play nice with tiling, so I can ignore them by default.

If "Ignored Programs" is not doing the trick you can add part of the window caption to the "Ignored Captions" list. If it doesn't help either, reply here and I'll download Wine and try to find the cause.

Also, make sure you have ", " (comma and space) between the ignored window names (f.ex. steam, wine, kate).

Example image of finding the proper class name for Atom. 
![Screenshot](http://i.imgur.com/BkIkopm.png)

**Comment by maxigaz** [comment]
Adding "thief2.exe" to the list of ignored programs did the trick. Also, I don't know what happened, but "steam" is finally picked up and ignored correctly. Thank you!

**Comment by Jazqa** [comment]
Glad to hear that! Sometimes ignoring a program might require multiple entries (f.ex "steam" and "Steam"). Programs are not very consistent with their window classes.
