### ISSUE TITLE
Top panel overlaps windows

### ISSUE THREAD

**Issue by zjeffer** [Jazqa/kwin-quarter-tiling#62]
I've been loving the script so far, but I have one problem with it:
I need to restart the script using 
> kwin_x11 --replace 

every time I reboot, because the windows don't adjust to the top panel. 

Using KDE Plasma, on Arch Linux version 4.15.3-2

If you need any more info please let me know :)
Thanks!

**Comment by zjeffer** [comment]
Here's a screenshot I recreated using the margin setting in the configuration menu:

https://imgur.com/hvQbnSK

**Comment by zjeffer** [comment]
I stopped having the issue a couple days after I opened this issue, so I'm going to close it.

**Comment by Jazqa** [comment]
Sorry for not responding earlier. I always see these issue reports on my phone and then forget about them when I get on my computer. Anyways, this occurs when the script starts before Plasma. Do you have many programs running on startup perhaps?

**Comment by zjeffer** [comment]
Here are my startup services: https://i.imgur.com/808Ney3.png and https://i.imgur.com/xxvpl8W.png.
Are there any I could disable that I don't need anyway?

**Comment by sohrob** [comment]
I'm having this same problem. Every time I reboot I need to disable the script and restart it in order for it work properly and not have windows be tucked under my top panel.

**Comment by sohrob** [comment]
> Sorry for not responding earlier. I always see these issue reports on my phone and then forget about them when I get on my computer. Anyways, this occurs when the script starts before Plasma. Do you have many programs running on startup perhaps?

I don't have many programs starting on startup (just Firefox) and this happens regularly. Is there a fix coming up? I also don't see any options button for creating padding. I'm running Debian Buster by the way.

**Comment by Jazqa** [comment]
Shouldn't happen anymore after 2.0. If it does, feel free to open this issue.
