### ISSUE TITLE
System settings modules

### ISSUE THREAD

**Issue by RaitaroH** [Jazqa/kwin-quarter-tiling#63]
So the script works well if you open System Settings, but for me anyway opening any component of the system settings seems to always make it float instead of tile.

**Comment by Crendgrim** [comment]
This happens because, when you start individual system settings module, they register their window as a "dialog window". Those usually should not get tiled.

**Comment by RaitaroH** [comment]
Would it be possible to add some INCLUDE PROGRAM SECTIONS in your settings. So is like exclude but inverted for such edge cases.

**Comment by Jazqa** [comment]
Sorry for spamming your email, even though you may not be using the script anymore. After a long hiatus, I started actively re-writing the script and am updating the tickets. 

As for the issue. I'm trying to avoid flooding up the settings menu. All that needs to be done for this feature is to find the line with `client.dialog` and remove it.
