### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by RaitaroH** [Jazqa/kwin-quarter-tiling#64]
I recommend adding discord to ignored applications. The reason why is because discord is opening 2 windows: updater and the normal one, thus when updater is closed you get moved back to the previous desktop. Trying adding updater to captions doesn't quite work either.

**Comment by Jazqa** [comment]
Great idea, I'll check out how Discord behaves as soon as I get my new system up and running.

**Comment by RaitaroH** [comment]
Nice.

Btw, great response time.

**Comment by RaitaroH** [comment]
Discord works nicely now. So I will close this. (maybe because I am not moved to the previous desktop anymore for some weird reason but alas)
