### ISSUE TITLE
Settings section for programs that the use would like to remove their titlebars

### ISSUE THREAD

**Issue by RaitaroH** [Jazqa/kwin-quarter-tiling#65]
So basically is like ignore, but this one should allow to have some programs that will have their titlebars removed. Right now I use a kwin rule.

**Comment by Jazqa** [comment]
I had an option to remove all titlebars in an earlier version, but I decided not to mess around with titlebars at all as the settings broke compatibility with other means of adjusting the titlebars.

**Comment by RaitaroH** [comment]
Very well then. Right now I am using another script that gets rid of them when maximized.... oh yeah, that means it won't quite work with this extension then huh. THUS another rule with regexp like: app1|app2|app3 is my only choice right now.
