### ISSUE TITLE
Moving to another desktop when the current is cleared and removing created desktops

### ISSUE THREAD

**Issue by RaitaroH** [Jazqa/kwin-quarter-tiling#66]
KDE Neon 5.12

So I created a few windows and populated all my 4 virtual desktops. After this new desktops are created they should be deleted after I close the applications. (not sure if you implemented this or not, I looked a bit through other issues)

On another note moving back to a desktop after windows are created is a bit... weird sometimes. Instead of going back one desktop instead I get back to the first even if I am on 4th desktop and the others have applications opened, not sure why. Also it does not happen every time. Yet again kinda weird.

Also yet another weird behavior is that sometime, a window is opened on say desktop 3 instead of 2 even thou 2 is clear... again, not every time.

**Comment by Jazqa** [comment]
I am not currently removing the desktops as it crashes KWin (the script keeps running though). I have not figured the reason for the crash. Anyways, I am aware the automatic desktop switching is very iffy and I am getting rid of it by default when rewriting the script.

**Comment by RaitaroH** [comment]
I actually stopped using the script for now because I kept being moved to random desktops...

**Comment by Jazqa** [comment]
Script doesn't adjust desktops anymore.
