### ISSUE TITLE
Moving through windows

### ISSUE THREAD

**Issue by RaitaroH** [Jazqa/kwin-quarter-tiling#67]
So I know you can move a window around, float it, make it bigger bla bla. But shouldn't there be some kind of shortcuts that will allow moving through windows ALT+TAB like. SO say I do shortcut and I circle through the window on screen.

**Comment by Crendgrim** [comment]
You can just use KWin's regular window movement shortcuts:
- The regular (default alt-tab) window switcher
- The alternative window switcher that you could configure to only list windows on the current workspace (I take it this is what you want?)
- Setting up the "go to left/right/top/bottom window" shortcuts in the Global Shortcuts module is very useful with this script
- I personally am also a fan of the "Show all windows" shortcut, where you can then type parts of the title of the window you want to switch to and activate using Enter

**Comment by RaitaroH** [comment]
Well I am already doing the above. I am saying is that it is more annoying to do the above rather than have a straightforward keyboard shortcut just for this.

**Comment by Jazqa** [comment]
I assume we are talking about switching the currently active window on the grid? Like the current movement keys, but switching the active window instead of moving any of the windows, right?

**Comment by RaitaroH** [comment]
Yes.

**Comment by Jazqa** [comment]
That is something I definitely have to add to the script. Especially if I plan on supporting more than four windows per desktop.

**Comment by barisdemirdelen** [comment]
@RaitaroH I don't exactly understand what you exactly need apart from the default kwin walk through windows shortcuts (alt+tab) and switch to window above/below/left/right shortcuts (I use meta + arrow keys). Care to elaborate more what exactly you would like?

**Comment by RaitaroH** [comment]
Many times alt+tab gets me the wrong window. I would like a shortcut that when I press it I know it is going to switch me to right side window for ex. The same way kwin has shortcuts for snapping to every edge and even corners there should be a way to switch focus to an window on the edges/corners.

**Comment by r00tdaemon** [comment]
I think this is already possible with meta+alt+arrow key
