### ISSUE TITLE
Window decoration used in store.kde.org screenshot?

### ISSUE THREAD

**Issue by paldepind** [Jazqa/kwin-quarter-tiling#68]
Hello @Jazqa. Thanks a lot for creating this great plugin :+1: 

I just noticed that in the screenshot [here](https://store.kde.org/p/1187647/) it appears that you have a setup without titlebars and where the active window has a distinct border color? How did you achieve that? I'd love to have a similar thing.

**Comment by Jazqa** [comment]
Titlebar: Go to 'Window Decoration' -> 'Window Specific Override' and add a new entry for `.*` for which you disable the title bar. [Picture.](https://user-images.githubusercontent.com/18004783/29276045-f64278ba-8115-11e7-99b2-7efe651e9efc.png)

Borders: Edit the following lines in `~/.config/kdeglobals` (if they don't exist, just add them under the [WM] category) `frame=r,g,b,a` and `inactiveFrame=r,g,b,a`

**Comment by paldepind** [comment]
Thanks a lot. Your instructions worked wonderfully :smile: My KDE setup just got even better.
