### ISSUE TITLE
UI won't show up

### ISSUE THREAD

**Issue by thunderactual** [Jazqa/kwin-quarter-tiling#71]
Hey, I am having issues with the configuration menu showing up. I did the cp command you have listed, but the cog won't show up when I am looking in "manage kwin scripts." Am I looking in the wrong place or what? Thanks!

**Comment by Jazqa** [comment]
Strange. Did you create the kservices folder before running the commands? Try running 

`ls ~/.local/share/kservices5`

to see if the script's .desktop file is there.

**Comment by Moanrisy** [comment]
Where to open configuration interface?
I can't find it in manage kwin script too

NVM

find the solution in
#37
