### ISSUE TITLE
With Live Tiling windows can't be moved as expected

### ISSUE THREAD

**Issue by alxlg** [Jazqa/kwin-quarter-tiling#72]
With Live Tiling I can resize a tiled window and the others will resize automatically while I am still resizing the first one. But with this option enabled I can't drag tiled windows anymore. Sometimes performing a dragging movement with the cursor exchange the position of the windows without moving them.

Is this a bug or am I missing something?

**Comment by barisdemirdelen** [comment]
What do you want to achieve by dragging a window? I thought the only reason to drag the window in a tiling setup would be to swap the windows positions as you described. If there is anything else or a bug in this please elaborate and i can have a look.

**Comment by alxlg** [comment]
@barisdemirdelen Thank you very much for your reply!
* With "Live Tiling" option disabled
   * when you drag a window it is moved following you cursor and eventually exchanged with another tiled window (perfect behavior)
   * when you resize a window the other ones are resized only when you stop resizing the first one (so no "live tiling")
* With "Live Tiling" option enabled
   * when you drag a window it doesn't follow your cursor but the windows got exchanged anyway (but not always, I'm not sure why)
   * when you resize a window the others are resized instantly while you are still resizing ("live tiling").

I would like to keep the dragging behavior that I have without "Live Tiling" while having "Live Tiling" for resizing (it seems to me the most logical behavior).

Do you know why enabling "Live TIling" change the dragging behavior?

**Comment by barisdemirdelen** [comment]
Ah i see. Well the reason it does that is because i thought live tiling would also live switch the positions and tile again. It makes sense to me when i use it. 

I think your request also makes sense to be able to drag the window as well as live tiling. Or maybe it is another idea to just have live resizing as you want?  

As for the sometimes not switching positions part, that may be a bug, i'm not sure.

**Comment by alxlg** [comment]
> makes sense to be able to drag the window as well as live tiling

Exactly, I don't see why I shouldn't have a feedback like window following my cursor. In fact it's only a matter of feedback and maybe since I don't have it I can't trigger the switch, or maybe it's a bug, I can't be sure at the moment.
