### ISSUE TITLE
More options for virtual desktops [wish]

### ISSUE THREAD

**Issue by smihael** [Jazqa/kwin-quarter-tiling#73]
- Add option to disable adding new virtual desktops automatically 
- Add option to add new desktops vertically and not horizontally (increase number of rows in pager)

**Comment by smihael** [comment]
The second option should be fairly easy to implement by adding  `ws.desktopGridHeight +=1` after `ws.desktops += 1`in the main.js.  It seems to work, but I haven't tested it yet extensively.

**Comment by lilianchiassai** [comment]
I second this request: having new virtual desktops opening automatically makes the script not so pleasant to use.

**Comment by Jazqa** [comment]
New version doesn't manage desktops.
