### ISSUE TITLE
[Feature Request] Option to have addditonal virtual desktop opened

### ISSUE THREAD

**Issue by r00tdaemon** [Jazqa/kwin-quarter-tiling#75]
A lot of times I want a blank virtual desktop(vd) opened so if I have 2 vd having some windows opened I would want a 3rd vd to be added to the pager automatically. 
Something what this script does https://store.kde.org/p/1158032/ but it doesn't work with quarter tiling so it would be nice to have this option in your script.

**Comment by Jazqa** [comment]
This script does not alter the amount of desktops anymore. It will work with the amount of desktops you have without adding or removing any.
