### ISSUE TITLE
Firefox Windows Being Sent to New Desktop on New Window

### ISSUE THREAD

**Issue by DanitiKain** [Jazqa/kwin-quarter-tiling#76]
https://streamable.com/o21nv

Here is a video that explains that problem.

Basically, if you have a window on the current desktop maximized it will send it to a newly opened window to a whole new virtual desktop.  I would like to make it so that if I open a new window no matter what the current status of the window is it will open tiled on the current desktop much like it would in i3.

**Comment by Jazqa** [comment]
Fixed in 2.0. Script doesn't alter the amount of desktops anymore and the desktop switching can be completely turned off.
