### ISSUE TITLE
Script crash when moving a window back to its original desktop

### ISSUE THREAD

**Issue by alxlg** [Jazqa/kwin-quarter-tiling#78]
Try this:
1. Open a window on desktop X
2. Move it to desktop Y
3. Move it back to desktop X
4. Notice that tiling doesn't work anymore, the script crashed and KWin needs to be restarted to reload the script

**Comment by rianneogi** [comment]
I'm having the same problem. The crash happens it step 2 itself (atleast for me), there is no need to move back to desktop X.
Is there any way to limit the number of desktops the script creates to 1? I want it to keep subdividing existing tiles without making a new desktop.

**Comment by Jazqa** [comment]
@rianneogi, there's a branch called [typescript-rework](https://github.com/Jazqa/kwin-quarter-tiling/tree/typescript-rework) I'm working on. It's basically the whole script rewritten from scratch and while it may lack some features and have some minor annoyances, it does not mess with desktops and it should be more stable than the original script.

If you feel like giving it a try, feel free to report any issues you face. Issues in the new branch are also much easier for me to fix than issues in the old version.

**Comment by Jazqa** [comment]
Should be fixed with the rewrite.
