### ISSUE TITLE
Konqueror breaks tiling

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#8]
I may be one of the not many KDE users that still have Konqueror as default web browser. There is "an easy way" to get external links to be opened in a single Konqueror window, which is to set "kfmclient newTab" as default web browser in KDE settings.

However, using this impairs tiling: it works fine when opening the first link, but Konqueror moves, breaking tiling rules when opening a 2nd, and successive external links.

Could you please try to reproduce the issue? I wouldn't ask if it wasn't because the browser is one of the most used applications, and I wouldn't like to change Konqueror as my default web app, neither to stop using tiling, if possible.

Thanks!

Edit: Oops, my first attempt for the title was "tiling and konqueror", and then I tried to be a bit more informative, but I got it the other way around, my bad :)

**Comment by kupiqu** [comment]
I have an intuition (most likely wrong or inaccurate) for why this might happen:

1. clicking on external link starts a kfmclient process
2. tiling rules may try to be applied to it, independently of the existing konqueror window
3. the link is, however, somehow transferred to konqueror's window
4. to which the tiling rule is not applied (anymore)

Would that make any sense?

**Comment by Jazqa** [comment]
I have no clue what is breaking the tiling in the first place, but I need to figure out the best API signal for re-tiling. Currently, I can fix this with a slight twitch. You'll see the tiling break but it'll re-tile itself in less than a second.

**Comment by Jazqa** [comment]
Found the cause and the signal it triggered. Should work now.

**Comment by kupiqu** [comment]
So amazing. Big thank you!!
