### ISSUE TITLE
no gaps in maximized windows 

### ISSUE THREAD

**Issue by da-viper** [Jazqa/kwin-quarter-tiling#83]
there is  no gaps when you maximize the window it only appears when you minimized and maximize the window .

video link 
https://streamable.com/h51wbr

**Comment by Jazqa** [comment]
The script is not altering maximized windows. There's no clean way to mess with the maximized windows, the closest way to implement what you're looking for is to have a shortcut for "fake maximize" that sets the window size to maximized minus gaps without actually setting the window state to maximized. 

However, I don't know why all of your windows are starting maximized. Does that happen without the script, or is the script causing it?

**Comment by da-viper** [comment]
How do I do what you said

**Comment by kupiqu** [comment]
I second this. It would be great to keep margins in maximized windows especially when using floating panels in latte 0.10, as it is my case now.

It would be great to give that as an option as your work around would not allow me to benefit from the "maxmize to new virtual desktop" script, which is actually very cool too.

**Comment by kupiqu** [comment]
> I second this. It would be great to keep margins in maximized windows especially when using floating panels in latte 0.10, as it is my case now.
> 
> It would be great to give that as an option as your work around would not allow me to benefit from the "maxmize to new virtual desktop" script, which is actually very cool too.

This would still be great to have but I feel it's less important now that I know there is an option in latte to remove the gap of floating panels for maximized windows :)

**Comment by kupiqu** [comment]
> > I second this. It would be great to keep margins in maximized windows especially when using floating panels in latte 0.10, as it is my case now.
> > It would be great to give that as an option as your work around would not allow me to benefit from the "maxmize to new virtual desktop" script, which is actually very cool too.
> 
> This would still be great to have but I feel it's less important now that I know there is an option in latte to remove the gap of floating panels for maximized windows :)

On second thought, this doesn't work very well as restoring windows from maximization don't get into proper tiling and one has to reset tiling every time.

Givent that I would prefer applying margins to maximized windows with this script than removing gaps of floating panels in latte

**Comment by kupiqu** [comment]
I opened this issue in latte-dock to see it this could be set there, but I think it might be out of latte scope:

https://bugs.kde.org/show_bug.cgi?id=419731

@Jazqa  perhaps the best solution would be to create an independent kwin script that would "simply" set margins to maximized clients

Unfortunately I never did a kwin script before. Do you have a feeling of how easy/difficult this could be?

**Comment by Jazqa** [comment]
Creating a new script would be the way to go, but even then I couldn’t identify maximized windows with this script. The maximized gaps would have to be smaller than the tiling gaps.

Messing with maximized windows makes detecting them difficult and causes minor visual annoyances (maximized windows have no shadows or rounded corners even if they would have gaps).

**Comment by kupiqu** [comment]
> Messing with maximized windows makes detecting them difficult and causes minor visual annoyances (maximized windows have no shadows or rounded corners even if they would have gaps).

One can keep shadows and rounded corners using Sierra Breeze Enhanced decorations: https://github.com/kupiqu/SierraBreezeEnhanced

Edit: the trick is just hiding the title bar but keeping everything else (borders, including rounded corners, and shadows)

**Comment by CarlosEkisde** [comment]
I was just trying the script today and I thought that was an intended behavior. In fact I think it's better to keep it that way since maximized windows should by definition fill the entire screen and to not being affected by tiling. Maximizing windows wouldn't have much sense if the window size is restricted I think.
