### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by ilkerhk** [Jazqa/kwin-quarter-tiling#87]
Hi there,
Keep up with the nice work. Here are a few issues: 

1- When I move a window to my current active virtual desktop using pager it is not tiling automatically. The new first floats, then I have to move one of the windows then the auto tiling kicks in

2- Shading unshading feature of Kwin is not working when the window is tiled. It leaves spaces and also when I unshade the window starts to float.

3- Connecting or disconnecting a monitor to my laptop messes up all the layouts. (I disable builtin monitor of the laptop and use an external monitor with a larger resolution.)

**Comment by Jazqa** [comment]
Thanks for the feedback. 

1. Looking into it!

2. Had no idea shading was a thing. I don't use it, so it's difficult to say how this should work. Should it be excluded from tiling while shaded and returned after unshaded, as if minimized?

3. I've been trying to fix this for most of the day but I've had no luck yet. I am able to listen to the monitor changes, but for some reason I get the wrong coordinates after the change. Still looking into it.

**Comment by ilkerhk** [comment]
Yes, shading solution you mentioned  would work for me.
Or alternatively, after  a window is shaded it tiles also. It's just the
titlebar when shaded, so it will tile above or below another window. When
unshaded instead of floating the window should tile in.
I usually use tiling to give another window more space, as an alternative
way to minimizing. But I can definitely live without it.

Best.

**Comment by Jazqa** [comment]
2 and 3 (shading support and monitor adjustments) should be in master now. However, monitor adjustments also have the issue specified in 1 (you need to move a window for them tile again).

**Comment by ilkerhk** [comment]
Got it. Thank you.
