### ISSUE TITLE
New client is not on focus when it requires moving to a different desktop

### ISSUE THREAD

**Issue by kupiqu** [Jazqa/kwin-quarter-tiling#89]
Please try to reproduce the issue as follows:

1. Move to an empty desktop
2. Open 4 clients, e.g. Konsole windows
3. Open a 5th one, which will move to a different desktop
4. Type `sth`

- Expected behavior: `sth` should appear in konsole
- Observed behavior: if the new desktop is empty, `sth` appears in krunner, otherwise it depends on the active client of the new desktop

**Comment by Jazqa** [comment]
Oh yeah, can reproduce 100% of the time. I’ll try to fix it asap.

**Comment by kupiqu** [comment]
Great, thank you :)

**Comment by Jazqa** [comment]
Should be okay now.

**Comment by kupiqu** [comment]
Excellent, thanks!!
