### ISSUE TITLE
Orphaned in AUR

### ISSUE THREAD

**Issue by mgurei** [Jazqa/kwin-quarter-tiling#91]
The project appears as orphaned in AUR, but I can see you are still maintaining it over here on GiuHub. The last upload on AUR seems to be from 07-2017.
It would be nice if you can keep it out up to date on AUR too, if possible, as this is quite definitely the best kwin tiling script I have found. Seeing an orphan project might discourage others to try it out.

**Comment by Jazqa** [comment]
As far as I know, the AUR script still pulls the newest code from this Github repository, so technically it hasn’t needed any changes since it’s creation. I’m not super familiar with AUR, but reuploading the script just because the source was updated would feel a little strange.

**Comment by mgurei** [comment]
I see. Sorry, I'm a newbie on the AUR system too, thank you for the clarification.

**Comment by Jazqa** [comment]
No worries! If you ever encounter any issues with the script, feel free to open an issue here. I appreciate every report! If using AUR, you should always be running the newest version of the script automatically (as long as you’ve updated your AUR installations) and all the issues you may face are still valid in the master branch.
