### ISSUE TITLE
Anyone interested in a 'Spiral Tiling' feature?

### ISSUE THREAD

**Issue by auwsom** [Jazqa/kwin-quarter-tiling#93]
https://github.com/kwin-scripts/kwin-tiling/issues/214

**Comment by Jazqa** [comment]
I usually use similar layout when working on a computer without a tiling script. `Alt+Tab` is not very convenient with a dozen windows open, so having a tiny bit of each window visible makes it easy to navigate between them with mouse. However, it is quite easy to maintain without a script, and moving/resizing functionality would be very different from tiling layouts.
