### ISSUE TITLE
Auto create virtual desktop

### ISSUE THREAD

**Issue by Ch4tul** [Jazqa/kwin-quarter-tiling#94]
Hi, i would like to know if the script can create new virtual desktops on demand, then delete them as they are not needed?
if the script is already able to do this, then this functionality is not working properly in my system, unless i manually create virtual desktops, the script wont try to create new ones, and will stack windows in the same virtual desktop.

Im using manjaro kde.

**Comment by Jazqa** [comment]
The script **used to** do that, but I removed the functionality in order to keep the scope as small as possible for easy maintenance. However, if you’ll create a few empty desktops, the script will move between them smoothly.
