### ISSUE TITLE
Windows retaining size on close

### ISSUE THREAD

**Issue by KaktusFeuer** [Jazqa/kwin-quarter-tiling#95]
Some applications are remembering their size when closed, notably "Kate" and "pamac." When the application is reopened it retains the size from when it was closed and does not tile correctly until the window is moved.

**Comment by Jazqa** [comment]
Kate has been a problem since the first version of the script and I suppose the Pamac case is similar. The script tries to resize the window, but the opened program insists on resizing itself. 

Anyways, I will leave this issue open and keep looking for a solution.
