### ISSUE TITLE
Avoiding fullscreen windows / set max height/width

### ISSUE THREAD

**Issue by hadallen** [Jazqa/kwin-quarter-tiling#96]
Hello, I really love this script however I wonder if there is some way to set a maximum width and height to certain windows. 

Example:
(https://imgur.com/a/uuBf3N3 for example images)

When I open my first window, 
If it is firefox:
it stays at half screen width and is centered horizontally on the screen

if it is dolphin, or konsole (for example), however
it stays at quarter tile size but is horizontally and vertically centered
opening another would have 2 quarter sized tiles, but vertically centered

---

I foresee issues however because it is often desirable to have my konsole window @ full screen height - which could possibly be catered to with a keyboard shortcut? (e.g. toggle window max height/width?)

I do not know how much work this would be or if it is even realistic, but I thought I would put it out there

**Comment by Jazqa** [comment]
Thanks for posting a feature suggestion! This feature is... kind of possible to implement, but quite challenging. You wouldn’t be able to set the maximum width/height via the script, but you’d be able to select programs that would not be stretched to the tiles (their initial size would be used instead). The script actually had a similar feature in an early version, but it was implemented quite poorly so I dropped it.

Anyways, this is a very good suggestion, so I’ll leave it open. Unfortunately, I don’t really have time to work on large features right now, so this’ll have to wait until I have a day to spare.

**Comment by drc0** [comment]
would it be possible instead to set a max width/height for **only the first program opened**? I noticed that on big screens when having only the browser open it is quite annoying having it maximized and I prefer instead to have it occupying only a part of the screen, maybe like the first example shown by OP.
