### ISSUE TITLE
Doesn't work when starting new session

### ISSUE THREAD

**Issue by akdor1154** [Jazqa/kwin-quarter-tiling#97]
Hey,
I'm completely new to plasma scripting so sorry I haven't looked into this in a technical sense. I'll start to have a play after work...
When installing Quarter-Tiling and activating it in the KWin Scripts control panel, everything works fine.
However, after this, when starting a new session, I get no tiling. I have to toggle Quarter-Tiling off then on again in the KWin Scripts panel for it to kick in.
Any pointers on how I can start to look into this?

Cheers
Jarrad
AwesomeWM refugee

**Comment by Jazqa** [comment]
Thanks for reporting the issue! Do you have anything special launching instantly after starting a session (programs, activities etc.) or are you starting an empty session?
