### ISSUE TITLE
Multi montior setup

### ISSUE THREAD

**Issue by quantumicrowave** [Jazqa/kwin-quarter-tiling#98]
Hi,
For multi-monitor setups, it would be ideal that you could choose between vertical splitting or horizontal spliting and to chose the amount of times a window splits horizontally before splitting vertically. For example, I have a 21:9 monitor vertically which can fit 3 windows stacked on top of each other confortably, however on my second monitor, (16:9) horizontal splitting doesn't make much sense. So the ideal would be to be able to chose the behaviour depending on the screen.
Let me know if this could be implemented or guide me for me to do it myself.
Thanks for reading

**Comment by Jazqa** [comment]
Sorry for the late response. This is something I've wanted to implement for a while and it's definitely on the top of the list of upcoming features.

**Comment by Jazqa** [comment]
Basically everything can be configured on a per-monitor basis in the Plasma 6 version of the script.
