### ISSUE TITLE
Slight update to the README

### ISSUE THREAD

**Issue by not-a-dev-stein** [Jazqa/kwin-quarter-tiling#99]
In the "Configuration" tab of the README it says everything can be configured through Kwin Scripts but there's an issue where, if you install the script through KDE Store (unsure if through the AUR it does the same) the user has to manually do `mkdir -p ~/.local/share/kservices5
ln -sf ~/.local/share/kwin/scripts/quarter-tiling/metadata.desktop ~/.local/share/kservices5/kwin-script/quarter-tiling.desktop` in order to get the configuration button to appear there.

It's not the biggest deal in the world but for inexperienced people like me it can be frustrating, it took me half an hour and Krohnkite's installation README to understand what those commands do.

**Comment by Jazqa** [comment]
It's in the README under installation. Do you feel like it'd be clearer under configuration?

**Comment by not-a-dev-stein** [comment]
I feel like a small acknowledgement either in installation or configuration would make it clearer.
For example:

> **Configuration**
The script is configured through the configuration interface under "Kwin Scripts". If you encounter programs that do not work with tiling, you can ignore them via the configuration interface. In case the configuration icon doesn't show, run `mkdir -p ~/.local/share/kservices5
ln -sf ~/.local/share/kwin/scripts/quarter-tiling/metadata.desktop ~/.local/share/kservices5/kwin-script-quarter-tiling.desktop` and open Kwin Scripts again.

What noobs would usually read in installation is just "options to install everything automatically" and "a bunch of commands to copy-paste if everything else doesn't work".

**Comment by Jazqa** [comment]
Alright, it's there now! Thanks for the heads-up, hopefully it'll save someone some time in the future!
